version: "3"

services:
  db:
    container_name: "tik-tack-mongo"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db: {}
