version: "3"

services:
  db:
    container_name: tik-tak-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tik-tak
    ports:
      - 27017:27017
      - 9229:9229
    volumes:
      - db:/data/db
  rest:
    container_name: tik-tack-api
    image: node:16
    command: yarn start:debug
    working_dir: /api/rest
    build:
      context: ./api/rest
    ports:
      - 8080:8080
    volumes:
      - ./api/rest:/api/rest:rw
    depends_on:
      - db
  ws:
    container_name: tik-tack-ws
    command: mix phx.server
    build:
      context: ./api/ws
    ports:
      - 4000:4000
    volumes:
      - ./api/ws:/api/ws:rw
    depends_on:
      - db

volumes:
  db: {}
